repository: dynamsoft-docs/document-normalizer-docs
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs/blob/v2
docFullPath: https://www.dynamsoft.com/document-normalizer/docs/v2/core
firstLevelUrl: /document-normalizer/docs/v2/core
docHomePage: /document-normalizer/docs/v2/core/
needSearchIndex: true
searchNeedFilter: true

introduction: /document-normalizer/docs/v2/core/introduction/


useVersionTree: false
isDCV: true
useJSVersionV3: true

assets: /document-normalizer/docs/v2/core/assets/
edit_icon: /document-normalizer/docs/v2/core/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/docs/v2/core/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/docs/v2/core/assets/img-icon/icon-sad.png

baseurl: "/document-normalizer/docs/v2/core"


plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "" 
    values: 
      docRootName: "Document Normalizer" 
      docHomePage: "/document-normalizer/docs/v2/core/introduction/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
